language: crystal

addons:
  apt:
    packages:
      - python-scipy
      - python-yaml
      - crystal
git:
  submodules: false

env:
  - TASK=bench LANG=java
  - TASK=style LANG=java
  - TASK=bench LANG=crystal
  - TASK=style LANG=crystal

install:
  - if [ "$TASK" = "bench" ]; then pip install --user ReBench; fi

script:
  - if [ "$TASK" = "bench" ]; then implementations/build-$LANG.sh && rebench -d test.conf test-java; fi
  - if [ "$TASK" = "style" ]; then implementations/build-$LANG.sh style; fi
