os: linux
dist: bionic
language: python

addons:
  apt:
    packages:
      - python-yaml

git:
  submodules: false

jobs:
  fast_finish: true
  include:
    - name: Crystal
      env: PLANG=crystal
      language: crystal
    - name: JavaScript
      env: PLANG=js
      language: node_js
      node_js: "13"
      install:
        - npm install -g jshint
    - name: Java
      env: PLANG=java  JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
      dist: trusty
    - name: SOM
      env: PLANG=som   JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
      dist: trusty
    - name: SOMns
      env: PLANG=somns JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
      dist: trusty
    - name: Pharo
      env: PLANG=pharo
      language: smalltalk
      smalltalk: Pharo32-7.0
    - name: Squeak 64-bit
      env: PLANG=squeak64
      language: smalltalk
      smalltalk: Squeak64-5.2
    - name: Squeak 32-bit
      env: PLANG=squeak32
      language: smalltalk
      smalltalk: Squeak32-5.2
    - name: RSqueak
      env: PLANG=rsqueak
      language: smalltalk
      smalltalk: Squeak32-5.2
      addons:
        apt:
          packages:
            - python-scipy
            - python-yaml
            - libsdl2-2.0-0
            - libffi6
    - name: Ruby
      env: PLANG=ruby
      language: ruby
      rvm: 2.6
      install:
        - gem install rubocop
    - name: Lua 5.2
      env: PLANG=lua52 LUA="lua=5.2"
      language: python
      python: 2.7
      before_install:
        # We use here before_install since we are in a virtualenv
        - pip install hererocks
        - pip install ReBench
        - hererocks here --$LUA -r latest
        - source here/bin/activate
        - luarocks install luacheck
        - ln -s "`which lua`" "`which lua`5.2"
  allow_failures:
    - env: PLANG=rsqueak

before_install:
  - pip install --user ReBench

script:
  - implementations/build-$PLANG.sh && rebench test.conf test-$PLANG
  - implementations/build-$PLANG.sh style
