os: linux
dist: bionic
language: python

addons:
  apt:
    packages:
      - python-yaml

git:
  submodules: false

jobs:
  fast_finish: true
  include:
    - env: PLANG=crystal
      language: crystal
    - env: PLANG=js
      language: node_js
      node_js: "6"
    - env: PLANG=java  JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: PLANG=som   JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: PLANG=somns JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: PLANG=pharo
      language: smalltalk
      smalltalk: Pharo32-7.0
    - env: PLANG=squeak64
      language: smalltalk
      smalltalk: Squeak64-5.2
    - env: PLANG=squeak32
      language: smalltalk
      smalltalk: Squeak32-5.2
    - env: PLANG=rsqueak
      language: smalltalk
      smalltalk: Squeak32-5.2
      addons:
        apt:
          packages:
            - python-scipy
            - python-yaml
            - libsdl2-2.0-0
            - libffi6
    - env: PLANG=ruby
      language: ruby
      rvm: 2.3.1
    - env: PLANG=lua52 LUA="lua=5.2"
      language: python
      python: 2.7
      before_install:
        - pip install hererocks
        - hererocks here --$LUA -r latest
        - source here/bin/activate
        - luarocks install luacheck
        - ln -s "`which lua`" "`which lua`5.2"
      install:
        - pip install ReBench
  allow_failures:
    - env: PLANG=rsqueak

install:
  - pip install --user ReBench
  - if [ "$PLANG" = "ruby" ]; then gem install rubocop;   fi
  - if [ "$PLANG" = "js" ];   then npm install -g jshint; fi

script:
  - implementations/build-$PLANG.sh && rebench test.conf test-$PLANG
  - implementations/build-$PLANG.sh style
