addons:
  apt:
    packages:
      - python-scipy
      - python-yaml

git:
  submodules: false

matrix:
  include:
    - env: PLANG=crystal
      language: crystal
    - env: PLANG=js
      language: node_js
      node_js: "6"
    - env: PLANG=java  JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: PLANG=som   JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: PLANG=somns JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      language: java
      jdk: oraclejdk8
    - env: PLANG=pharo
      language: smalltalk
      smalltalk: Pharo-5.0
    - env: PLANG=squeak
      language: smalltalk
      smalltalk: Squeak-5.1
    - env: PLANG=rsqueak
      language: smalltalk
      smalltalk: Squeak-5.1
      addons:
        apt:
          packages:
            - python-scipy
            - python-yaml
            - libsdl2-2.0-0
            - libffi6
    - env: PLANG=ruby
      language: ruby
      rvm: 2.3.1

install:
  - pip install --user ReBench
  - if [ "$PLANG" = "ruby" ]; then gem install rubocop;   fi
  - if [ "$PLANG" = "js" ];   then npm install -g jshint; fi

script:
  - implementations/build-$PLANG.sh && rebench test.conf test-$PLANG
  - implementations/build-$PLANG.sh style
