language: crystal
jdk:
  - oraclejdk8
node_js:
  - "6"

addons:
  apt:
    packages:
      - python-scipy
      - python-yaml

git:
  submodules: false

env:
  - LANG=crystal
  - LANG=java
  - LANG=js
  - LANG=ruby
  - LANG=som
  - LANG=somns

install:
  - pip install --user ReBench
  - if [ "$LANG" = "ruby" ]; then rvm use 2.3.1 --install --binary --fuzzy && gem install rubocop; fi
  - if [ "$LANG" = "js" ]; then pwd; npm install jshint; fi
  - if [ "$LANG" = "som" ] || [ "$LANG" = "somns" ]; then jdk_switcher use oraclejdk8; fi

script:
  - implementations/build-$LANG.sh && rebench test.conf test-$LANG
  - implementations/build-$LANG.sh style
