addons:
  apt:
    packages:
      - python-scipy
      - python-yaml
git:
  submodules: false

env:
  - TASK=java-bench
  - TASK=java-style

install:
  - pip install --user ReBench

script:
  - if [ "$TASK" = "java-bench" ]; then (cd benchmarks/Java && ant jar) && rebench -d test.conf test-java; fi
  - if [ "$TASK" = "java-style" ]; then cd benchmarks/Java && ant checkstyle-jar && ant checkstyle; fi
